FROM node:20-bookworm-slim

WORKDIR /app
RUN apt-get update && apt-get install -y --no-install-recommends curl \
  && rm -rf /var/lib/apt/lists/*

COPY package.json package-lock.json ./
COPY shared ./shared
COPY api ./api
COPY web ./web

RUN npm ci --omit=dev

WORKDIR /app/api

ENV NODE_ENV=development
EXPOSE 4001
ENV PORT=4001

CMD ["node", "server.js"]
